This function receive one value as string

    This function prints a text with 2 new lines
    after each of these characters: ., ? and :
    text must be a string,
    otherwise raise a TypeError exception with the message:
    "text must be a string"
    There should be no space at the beginning
    or at the end of each printed line

Importing module print_square

>>> ti = __import__('5-text_indentation').text_indentation

Now, doing tests

>>> ti("""Lorem ipsum dolor sit amet, consectetur adipiscing elit. \
... Quonam modo? Utrum igitur tibi litteram videor an totas paginas commovere? \
... Non autem hoc: igitur ne illud quidem. Fortasse id optimum, sed ubi illud: \
... Plus semper voluptatis? Teneo, inquit, finem illi videri nihil dolere. \
... Transfer idem ad modestiam vel temperantiam, quae est moderatio cupiditatum \
... rationi oboediens. Si id dicis, vicimus. Inde sermone vario sex illa a Dipylo \
... stadia confecimus. Sin aliud quid voles, postea. Quae animi affectio suum \
... cuique tribuens atque hanc, quam dico. Utinam quidem dicerent alium alio \
... beatiorem! Iam ruinas videres""")
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Quonam modo?

Utrum igitur tibi litteram videor an totas paginas commovere?

Non autem hoc:

igitur ne illud quidem.

Fortasse id optimum, sed ubi illud:

Plus semper voluptatis?

Teneo, inquit, finem illi videri nihil dolere.

Transfer idem ad modestiam vel temperantiam, quae est moderatio cupiditatum rationi oboediens.

Si id dicis, vicimus.

Inde sermone vario sex illa a Dipylo stadia confecimus.

Sin aliud quid voles, postea.

Quae animi affectio suum cuique tribuens atque hanc, quam dico.

Utinam quidem dicerent alium alio beatiorem! Iam ruinas videres>>> ti()
Traceback (most recent call last):
    ...
TypeError: text_indentation() missing 1 required positional argument: 'text'

>>> ti(1)
Traceback (most recent call last):
    ...
TypeError: text must be a string

>>> ti(2.59)
Traceback (most recent call last):
    ...
TypeError: text must be a string

>>> ti(abc)
Traceback (most recent call last):
    ...
NameError: name 'abc' is not defined
